source 'https://rubygems.org'

gem 'rails', '~> 4.1.6'
gem 'pg', '~> 0.17.1'
gem 'google-api-client', '~> 0.7.1'
gem 'oj', '~> 2.11.1'

group :development, :test do
  gem 'dotenv-rails', '~> 1.0.2'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'pry-rails', '~> 0.3.2'
end

group :development do
  gem 'spring', '~> 1.1.3'
end

group :test do
  gem 'vcr', '~> 2.9.3'
  gem 'webmock', '~> 1.20.4'
end